### ISSUE TITLE
Future support for BAM-formatted subreads

### ISSUE THREAD

**Issue by dbrowneup** [fenderglass/Flye#13]
Hi guys, thanks for the fantastic piece of software, it works beautifully. I am just wondering if you plan to add support for subreads in the PacBio BAM format? Lots of information contained in the BAM file could probably be used to help improve the assembly.

**Comment by fenderglass** [comment]
Hi,

Thank you! This definitely would be a nice feature to have, probably we will incorporate it in one of the future releases.

**Comment by harish0201** [comment]
@dbrowneup 

Just curious, would that entail converting the BAM on the fly to fasta and running the assembly?

If not doesn't dextract offer the same functionality?

**Comment by mikolmogorov** [comment]
Looks like there are no benefits of having BAMs instead of fasta/q as input. The extra information from BAM could be used for polishing, but we currently don't plan to extend Flye polisher to use it, as there are already a few good tools for this task (like Quiver). Closing for now.
