### ISSUE TITLE
Why the decision to use minimap2 as replacement for BLASR?

### ISSUE THREAD

**Issue by MichaelsGITIGIT** [fenderglass/Flye#20]
I am wondering why you decided to use minimap2 as a replacement for BLASR. I know, BLASR is designed for PacBio data, so BLASR is not the right choice for ONP data. Also I am aware of the fact, that minimap2 is super fast.

However, can you elaborate a bit on why you did not choose GraphMap as a replacement? Isn't it more sensitive than minimap2?

It might even be an option to incorporate GraphMap as well and let the user to choose? :-) Though this means quite some work on your side I guess...

**Comment by fenderglass** [comment]
Well, the initial choice was pretty much arbitrary - we were looking for a BLASR replacement. I did not do any benchmarks myself, but according to Heng Li's preprint minimap2 is more sensitive - https://arxiv.org/abs/1708.01492. Plus, it is easier to integrate into the existing codebase (less extra dependencies). If you feel that GraphMap should work better, you are always welcome to propose changes via pull request :)
